### ISSUE TITLE
Tool does not migrate private datasets

### ISSUE THREAD

**Issue by shevron** [datopian/migrate-metadata#11]
The API used by the tool to migrate datasets will not include any private datasets. 

## Acceptance 

* [ ] All datasets in a CKAN instance are migrated including private ones
* [ ] Optionally, add a command line option to decide whether to include private datasets

## Analysis
Possible solution is to switch from the `package_list` API to fetching a list of organizations (`organization_list`) and then calling `group_package_show` for each org. Need to validate that this works.

**Comment by rufuspollock** [comment]
@uwaheed88 could you look into this.

**Comment by pdelboca** [comment]
Implemented in #14
